version: '3'

services:
  testeredis-compose:
    image: redis:alpine
    ports:
      - "16379:6379"
    networks:
      - databases

  testemongo-compose:
    image: mongo
    ports:
      - "37017:27017"
    networks:
      - databases

  testesqlserver2017-compose:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      SA_PASSWORD: "DockerSql2017!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "21433:1433"
    networks:
      - databases
      
networks: 
    databases:
        driver: bridge
